### ISSUE TITLE
Erro ao tentar cadastrar curso

### ISSUE THREAD

**Issue by larissamato** [coutinhonobre/WebServiceSpring#20]
Ao tentar cadastrar o curso o backend apresenta erro 500, além disso não existe no frontend nenhum alerta informando o usuário que ocorreu um erro interno. Segue o print: 

![Image](https://github.com/coutinhonobre/WebServiceSpring/assets/65307102/56e0e974-e606-4b32-a4a1-9157c0df5a90)

![Image](https://github.com/coutinhonobre/WebServiceSpring/assets/65307102/1b3878b7-89cd-46cc-a597-9e7520c11b09)

Response => {"timestamp":"2023-11-08T21:02:55.709+00:00","status":500,"error":"Internal Server Error","path":"/sistema-academico/cursos"}

**Comment by HeryckMbs** [comment]
Este erro acontece por configuração de banco de dados errada
